# Copyright (C) 2020 Open Source Integrators
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

from odoo import fields, models


class ALNApartment(models.Model):
    _name = "aln.apartment"
    _description = "ALN Apartment"

    apartment_id_txt = fields.Char('Apartment ID')
    last_update_date = fields.Datetime(string="Last Update Date")
    last_contacted_date = fields.Datetime(string="Last Contacted Date")
    row_version = fields.Integer('Row Version')
    aln_id_txt = fields.Char('ALN')
    status = fields.Char('Status')
    apt_name = fields.Char('Apt Name')
    fka = fields.Char('FKA')
    hours = fields.Char('Hours')
    email = fields.Char('Email')
    market = fields.Char('Market')
    apt_owner_id_txt = fields.Char('Apt Owner')
    submarket_id_txt = fields.Char('Submarket')
    industry_id = fields.Many2one('res.partner.industry', 'SubMarket ID')
    corporate_mngmt_cmpny_id = fields.Many2one('res.partner', 'Corporate Mng Company')
    regional_mngmt_cmpny_id = fields.Many2one('res.partner', 'Regional Mng Company')
    num_of_units = fields.Char('Num of Units')
    year_built = fields.Char('Year Built')
    year_remodeled = fields.Char('Year Remodeled')
    timezone = fields.Char('TimeZone')
    occupancy = fields.Char('Occupancy')
    number_of_stories = fields.Char('Number Of Stories')
    directions = fields.Char('Directions')
    property_description = fields.Char('Property Description')
    apt_homepage = fields.Char('Apt Home Page')
    apt_picture_url = fields.Char('Apt Picture URL')
    curr_manager = fields.Char('Curr Manager')
    areasupervisor_id_txt = fields.Char('Area Supervisor')
    areasupervisor_id = fields.Many2one('res.partner', 'Area Supervisor ID')
    regional_management_company_id_txt = fields.Char('Regional Management Company')
    corporate_management_company_id_txt = fields.Char('Corporate Management Company')
    owner_id_txt = fields.Char('Owner')
    views = fields.Char('Views')
    ac_heating = fields.Char('AC Heating')
    map_coordinates = fields.Char('Map Coordinates')
    other_notes = fields.Char('Other Notes')
    average_rent = fields.Char('Average Rent')
    average_sqft = fields.Char('Average SqFt')
    mkt_pct_rff_rentunit = fields.Char('Mkt Pct Eff Rent Unit')
    mkt_pct_rff_rentsqft = fields.Char('Mkt Pct Eff Rent SqFt')
    sub_mkt_pct_rff_rentunit = fields.Char('Sub Mkt Pct Eff Rent Unit')
    sub_mkt_pct_rff_rentsqft = fields.Char('Sub Mkt Pct Eff Rent SqFt')
    mkt_pct_net_rentunit = fields.Char('Mkt Pct Net Rent Unit')
    mkt_pct_net_rentsqft = fields.Char('Mkt Pct Net Rent SqFt')
    sub_mkt_net_rff_rentunit = fields.Char('Sub Mkt Pct Net Rent Unit')
    sub_mkt_net_rff_rentsqft = fields.Char('Sub Mkt Pct Net Rent SqFt')
    pricing_avail_website = fields.Char('Pricing And Avail Website')
    pricing_avail_website_alt = fields.Char('Pricing And Avail Website Alt')
    rms_id_txt = fields.Char('RMS')
    rms_program = fields.Char('RMS Program')
    pricing_tier = fields.Char('Pricing Tier')
    asset_fee_managed = fields.Char('Asset Or Fee Managed')
    county = fields.Char('County')
    gps_latitude = fields.Char('GPS Latitude')
    gps_longitude = fields.Char('GPS Longitude')
    pmsa = fields.Char('PMSA')
    pmsa_description = fields.Char('PMSA Description')
    cmsa = fields.Char('CMSA')
    census_block = fields.Char('Census Block')
    census_tract = fields.Char('Census Tract')
    county_fips_code = fields.Char('County FIPS Code')
    physical_address_to = fields.Char('Physical Address To')
    physical_address_line1 = fields.Char('Physical Address Line1')
    physical_address_line2 = fields.Char('Physical Address Line2')
    physical_address_city = fields.Char('Physical Address City')
    physical_address_state = fields.Char('Physical Address State')
    physical_address_zip = fields.Char('Physical Address ZIP')
    mailing_address_to = fields.Char('Mailing Address To')
    mailing_address_line1 = fields.Char('Mailing Address Line1')
    mailing_address_line2 = fields.Char('Mailing Address Line2')
    mailing_address_city = fields.Char('Mailing Address City')
    mailing_address_state = fields.Char('Mailing Address State')
    mailing_address_zip = fields.Char('Mailing Address ZIP')
    shipping_address_to = fields.Char('Shipping Address To')
    shipping_address_line1 = fields.Char('Shipping Address Line1')
    shipping_address_line2 = fields.Char('Shipping Address Line2')
    shipping_address_city = fields.Char('Shipping Address City')
    shipping_address_state = fields.Char('Shipping Address State')
    shipping_address_zip = fields.Char('Shipping Address ZIP')
    property_phone = fields.Char('Property Phone')
    property_fax = fields.Char('Property Fax')
    apt_last_changed_date = fields.Datetime(string="Last changed Date")
    apt_published_date = fields.Datetime(string="Published Date")
    apt_published_id = fields.Many2one(
        'res.partner',
        'Published by'
    )
    apt_state = fields.Selection(
        [('published', 'Published'),
         ('unpublished', 'Unpublished')],
        string='State',
        default='unpublished'
    )
